language: cpp
sudo: false

compiler:
  - clang
  - gcc

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - g++-4.9
      - clang-3.5

before_install:
  - if [ "$CXX" == "g++" ]; then
        export CXX=g++-4.9;
        export CC=gcc-4.9;
    elif [ "$CXX" == "clang++" ]; then
        export CXX=clang++-3.5;
        export CC=clang-3.5;
    fi
  - echo "$CXX $CC"

script:
  #############################################################################
  - cd projects/gcc/Test
  - make CC=$CXX
  - cd -
  #############################################################################
  - cd projects/gcc/Time
  - make CC=$CXX
  - cd -
